# ========================================
# Bloatware Remove Script
# ========================================
# Reads bloatware_list.csv and uninstalls the
# enabled legacy desktop applications by invoking
# their QuietUninstallString or UninstallString.
#
# NOTES:
# - Administrator privileges are required.
# - Entries with NoRemove=1 or SystemComponent=1
#   are automatically skipped for safety.
# - bloatware_list.csv is typically generated by
#   the App Inventory Export module and edited by
#   the operator (set Enabled=1 for targets).
# ========================================

Write-Host ""
Show-Separator
Write-Host "Bloatware Remove" -ForegroundColor Cyan
Show-Separator
Write-Host ""


# ========================================
# Helper: Normalize registry path to PS drive format
# Converts HKEY_LOCAL_MACHINE\... → HKLM:\...  etc.
# Ensures Test-Path works regardless of CSV origin.
# ========================================
function ConvertTo-PsRegistryPath {
    param([string]$Path)
    return $Path `
        -replace '^HKEY_LOCAL_MACHINE\\', 'HKLM:\' `
        -replace '^HKEY_CURRENT_USER\\',  'HKCU:\' `
        -replace '^HKEY_CLASSES_ROOT\\',  'HKCR:\' `
        -replace '^HKEY_USERS\\',         'HKU:\'
}


# ========================================
# Helper: Auto-quote unquoted executable paths
# Some registry UninstallStrings omit quotes around
# paths that contain spaces. cmd.exe /c splits on
# the first space and fails to locate the binary.
# Already-quoted strings are returned unchanged.
# ========================================
function Invoke-QuoteUninstallPath {
    param([string]$CmdString)

    # Already quoted → return as-is (covers most entries)
    if ($CmdString -match '^"') { return $CmdString }

    # Drive-rooted path: extract up to the .exe/.bat/.cmd/.msi boundary,
    # then quote the executable portion, preserving any trailing arguments.
    if ($CmdString -match '^([A-Za-z]:\\.+?\.(?:exe|bat|cmd|msi))(\s+.*)?$') {
        $exePart = $Matches[1].Trim()
        $argPart = if ($Matches[2]) { $Matches[2].Trim() } else { "" }
        if ($argPart) {
            return "`"$exePart`" $argPart"
        } else {
            return "`"$exePart`""
        }
    }

    # Not a recognized pattern (e.g. bare command name) → return unchanged
    return $CmdString
}


# ========================================
# Step 1: CSV load
# ========================================
$csvPath = Join-Path $PSScriptRoot "bloatware_list.csv"

$enabledItems = Import-ModuleCsv -Path $csvPath -FilterEnabled `
    -RequiredColumns @("Enabled", "DisplayName", "UninstallString")

if ($null -eq $enabledItems) {
    return (New-ModuleResult -Status "Error" -Message "Failed to load bloatware_list.csv")
}
if ($enabledItems.Count -eq 0) {
    return (New-ModuleResult -Status "Skipped" -Message "No enabled entries")
}


# ========================================
# Step 2: Pre-flight check
# ========================================
if (-not (Test-AdminPrivilege)) {
    Show-Error "Administrator privileges are required to uninstall applications."
    Write-Host ""
    return (New-ModuleResult -Status "Error" -Message "Administrator privileges required")
}


# ========================================
# Step 3: Pre-execution display
# ========================================
Write-Host "----------------------------------------" -ForegroundColor White
Write-Host "Uninstall Targets" -ForegroundColor Cyan
Write-Host "----------------------------------------" -ForegroundColor White
Write-Host ""

foreach ($item in $enabledItems) {
    $displayName = if ($item.Description) { $item.Description } else { $item.DisplayName }

    # Safety skip flags
    if ($item.NoRemove -eq "1") {
        Write-Host "  [SKIP] $displayName" -ForegroundColor DarkGray
        Write-Host "    Reason: NoRemove=1" -ForegroundColor DarkGray
        Write-Host ""
        continue
    }
    if ($item.SystemComponent -eq "1") {
        Write-Host "  [SKIP] $displayName" -ForegroundColor DarkGray
        Write-Host "    Reason: SystemComponent=1" -ForegroundColor DarkGray
        Write-Host ""
        continue
    }

    # Idempotency check
    $isInstalled = $true
    if (-not [string]::IsNullOrWhiteSpace($item.RegistryKey)) {
        $psRegKey    = ConvertTo-PsRegistryPath $item.RegistryKey
        $isInstalled = Test-Path $psRegKey
    }

    # Determine display method label
    $method = if (-not [string]::IsNullOrWhiteSpace($item.QuietUninstallString)) {
        "QuietUninstall"
    } elseif ($item.WindowsInstaller -eq "1") {
        "MSI (/qn)"
    } elseif (-not [string]::IsNullOrWhiteSpace($item.UninstallString)) {
        "Uninstall"
    } else {
        "No uninstall string"
    }

    if ($isInstalled) {
        Write-Host "  [INSTALLED] $displayName" -ForegroundColor Yellow
        Write-Host "    Publisher: $($item.Publisher)" -ForegroundColor DarkGray
        Write-Host "    Method:    $method" -ForegroundColor DarkGray
    } else {
        Write-Host "  [NOT FOUND] $displayName" -ForegroundColor DarkGray
        Write-Host "    (Already uninstalled or not present)" -ForegroundColor DarkGray
    }
    Write-Host ""
}

Write-Host "----------------------------------------" -ForegroundColor White
Write-Host ""


# ========================================
# Step 4: Confirmation
# ========================================
$cancelResult = Confirm-ModuleExecution -Message "Uninstall the applications listed above?"
if ($null -ne $cancelResult) { return $cancelResult }

Write-Host ""


# ========================================
# Step 5: Uninstall loop
# ========================================
$successCount = 0
$skipCount    = 0
$failCount    = 0

foreach ($item in $enabledItems) {
    $displayName = if ($item.Description) { $item.Description } else { $item.DisplayName }

    Write-Host "----------------------------------------" -ForegroundColor White
    Write-Host "Processing: $displayName" -ForegroundColor Cyan
    Write-Host "----------------------------------------" -ForegroundColor White

    # ----------------------------------------
    # Safety skip checks (outside try)
    # ----------------------------------------
    if ($item.NoRemove -eq "1") {
        Show-Skip "Skipped: NoRemove=1"
        Write-Host ""
        $skipCount++
        continue
    }
    if ($item.SystemComponent -eq "1") {
        Show-Skip "Skipped: SystemComponent=1"
        Write-Host ""
        $skipCount++
        continue
    }

    # Idempotency: verify still installed
    if (-not [string]::IsNullOrWhiteSpace($item.RegistryKey)) {
        $psRegKey = ConvertTo-PsRegistryPath $item.RegistryKey
        if (-not (Test-Path $psRegKey)) {
            Show-Skip "Already uninstalled (registry key not found)"
            Write-Host ""
            $skipCount++
            continue
        }
    }

    # ----------------------------------------
    # Determine uninstall method
    # ----------------------------------------
    $useMethod = ""
    $cmdString = ""
    $msiGuid   = ""

    if (-not [string]::IsNullOrWhiteSpace($item.QuietUninstallString)) {
        # Priority 1: QuietUninstallString
        $useMethod = "quiet"
        $cmdString = $item.QuietUninstallString
    } elseif ($item.WindowsInstaller -eq "1" -and -not [string]::IsNullOrWhiteSpace($item.UninstallString)) {
        # Priority 2: MSI — extract GUID for silent uninstall
        if ($item.UninstallString -match '\{[0-9A-Fa-f\-]+\}') {
            $useMethod = "msi"
            $msiGuid   = $Matches[0]
        } else {
            Show-Warning "MSI GUID not found in UninstallString. Falling back to standard method."
            $useMethod = "standard"
            $cmdString = $item.UninstallString
        }
    } elseif (-not [string]::IsNullOrWhiteSpace($item.UninstallString)) {
        # Priority 3: UninstallString as-is
        $useMethod = "standard"
        $cmdString = $item.UninstallString
    } else {
        Show-Skip "No uninstall string available"
        Write-Host ""
        $skipCount++
        continue
    }

    # ----------------------------------------
    # Execute uninstall
    # ----------------------------------------
    try {
        $proc = $null

        switch ($useMethod) {
            "quiet" {
                $cmdToRun = Invoke-QuoteUninstallPath $cmdString
                Show-Info "Method: QuietUninstall"
                Show-Info "Command: $cmdToRun"
                $proc = Start-Process -FilePath "cmd.exe" `
                    -ArgumentList @("/c", $cmdToRun) `
                    -Wait -NoNewWindow -PassThru -ErrorAction Stop
            }
            "msi" {
                $msiArgs = "/X$msiGuid /qn /norestart"
                Show-Info "Method: MSI (/qn)"
                Show-Info "Command: msiexec.exe $msiArgs"
                $proc = Start-Process -FilePath "msiexec.exe" `
                    -ArgumentList $msiArgs `
                    -Wait -NoNewWindow -PassThru -ErrorAction Stop
            }
            "standard" {
                $cmdToRun = Invoke-QuoteUninstallPath $cmdString
                Show-Info "Method: Uninstall"
                Show-Info "Command: $cmdToRun"
                $proc = Start-Process -FilePath "cmd.exe" `
                    -ArgumentList @("/c", $cmdToRun) `
                    -Wait -NoNewWindow -PassThru -ErrorAction Stop
            }
        }

        switch ($proc.ExitCode) {
            0 {
                Show-Success "$displayName uninstalled successfully (ExitCode: 0)"
                $successCount++
            }
            3010 {
                Show-Success "$displayName uninstalled successfully (ExitCode: 3010)"
                Show-Warning "A reboot is required to complete the uninstallation."
                $successCount++
            }
            default {
                Show-Error "$displayName completed with ExitCode: $($proc.ExitCode)"
                Show-Info "Check application logs for details."
                $failCount++
            }
        }
    }
    catch {
        Show-Error "Failed: $displayName : $_"
        $failCount++
    }

    Write-Host ""
}


# ========================================
# Step 6: Result
# ========================================
return (New-BatchResult -Success $successCount -Skip $skipCount -Fail $failCount `
    -Title "Bloatware Remove Results")
