# ========================================
# Startup Command Deploy Script
# ========================================
# Generates a one-time execution script from CSV command entries,
# deploys it to C:\ProgramData\fabriq\, and sets up the
# Default User Startup trigger via existing fabriq infrastructure.
#
# Leverages Deploy-FabriqUserSetupLauncher and Deploy-FabriqStartupTrigger
# from kernel/common.ps1 (same pattern as reg_hkcu_config).
# ========================================

Write-Host ""
Show-Separator
Write-Host "Startup Command Deploy" -ForegroundColor Cyan
Show-Separator
Write-Host ""

# ========================================
# Step 1: Load CSV
# ========================================
$csvPath = Join-Path $PSScriptRoot "startup_command_list.csv"

$enabledItems = Import-ModuleCsv -Path $csvPath -FilterEnabled `
    -RequiredColumns @("Enabled", "Order", "Description", "Command")

if ($null -eq $enabledItems) {
    return (New-ModuleResult -Status "Error" -Message "Failed to load startup_command_list.csv")
}
if ($enabledItems.Count -eq 0) {
    return (New-ModuleResult -Status "Skipped" -Message "No enabled entries")
}

# Sort by Order column
$enabledItems = @($enabledItems | Sort-Object { [int]$_.Order })

# ========================================
# Step 2: Prerequisite Check
# ========================================
if (-not (Test-AdminPrivilege)) {
    Show-Error "Administrator privileges required for Default User Startup deployment"
    Write-Host ""
    return (New-ModuleResult -Status "Error" -Message "Administrator privileges required")
}

# ========================================
# Step 3: Display Target Commands
# ========================================
$scriptDir  = "C:\ProgramData\fabriq"
$scriptPath = Join-Path $scriptDir "apply_startup_commands.ps1"
$scriptExists = Test-Path $scriptPath

Write-Host "========================================" -ForegroundColor Yellow
Write-Host "Commands to deploy for new user first logon" -ForegroundColor Yellow
Write-Host "  Deploy to: $scriptPath" -ForegroundColor Yellow
if ($scriptExists) {
    Write-Host "  Status: [OVERWRITE] Script already exists" -ForegroundColor DarkYellow
}
Write-Host "========================================" -ForegroundColor Yellow
Write-Host ""

foreach ($item in $enabledItems) {
    $displayName = if ($item.Description) { $item.Description } else { $item.Command }

    Write-Host "  [APPLY] [$($item.Order)] $displayName" -ForegroundColor Yellow
    Write-Host "    Command: $($item.Command)" -ForegroundColor DarkGray
    Write-Host ""
}

Write-Host "========================================" -ForegroundColor Yellow
Write-Host ""

# ========================================
# Step 4: Confirmation
# ========================================
$cancelResult = Confirm-ModuleExecution -Message "Deploy the above commands for new user startup execution?"
if ($null -ne $cancelResult) { return $cancelResult }

Write-Host ""

# ========================================
# Step 5: Generate and Deploy
# ========================================
$successCount = 0
$skipCount    = 0
$failCount    = 0

# --- 5a: Generate apply_startup_commands.ps1 ---
Write-Host "----------------------------------------" -ForegroundColor White
Write-Host "Generating startup command script" -ForegroundColor Cyan
Write-Host "----------------------------------------" -ForegroundColor White

try {
    # Build command entries as PowerShell array literal
    $commandEntries = @()
    foreach ($item in $enabledItems) {
        # Escape single quotes in command string
        $escapedCommand = $item.Command -replace "'", "''"
        $escapedDesc    = $item.Description -replace "'", "''"
        $commandEntries += "    @{ Order=[int]'$($item.Order)'; Description='$escapedDesc'; Command='$escapedCommand' }"
    }
    $commandBlock = $commandEntries -join "`n"

    $scriptContent = @"
# ========================================
# Fabriq Startup Commands (Auto-generated)
# ========================================
# Generated by startup_command_config module.
# Executed once at new user first logon via fabriq_user_setup.ps1.
# Do not edit manually - regenerate from CSV instead.
# ========================================

`$logDir  = Join-Path `$env:LOCALAPPDATA "fabriq"
`$logFile = Join-Path `$logDir "startup_commands.log"

if (-not (Test-Path `$logDir)) {
    New-Item -Path `$logDir -ItemType Directory -Force | Out-Null
}

function Write-CmdLog {
    param([string]`$Message)
    `$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    "`$timestamp `$Message" | Add-Content -Path `$logFile -Force -Encoding UTF8
}

Write-CmdLog "===== Startup Commands Begin ====="

`$commands = @(
$commandBlock
)

foreach (`$cmd in (`$commands | Sort-Object { `$_.Order })) {
    Write-CmdLog "Executing [`$(`$cmd.Order)] `$(`$cmd.Description)"
    try {
        cmd.exe /c `$cmd.Command
        Write-CmdLog "  Result: Success (ExitCode: `$LASTEXITCODE)"
    }
    catch {
        Write-CmdLog "  Result: Error - `$(`$_.Exception.Message)"
    }
}

Write-CmdLog "===== Startup Commands End ====="
"@

    if (-not (Test-Path $scriptDir)) {
        New-Item -Path $scriptDir -ItemType Directory -Force | Out-Null
    }
    $scriptContent | Set-Content -Path $scriptPath -Force -Encoding UTF8
    Show-Success "Script generated: $scriptPath ($($enabledItems.Count) commands)"
    $successCount++
}
catch {
    Show-Error "Failed to generate script: $_"
    $failCount++
    Write-Host ""
    return (New-BatchResult -Success $successCount -Skip $skipCount -Fail $failCount -Title "Startup Command Deploy Results")
}

Write-Host ""

# --- 5b: Deploy Launcher ---
Write-Host "----------------------------------------" -ForegroundColor White
Write-Host "Deploying user setup launcher" -ForegroundColor Cyan
Write-Host "----------------------------------------" -ForegroundColor White

$launcherResult = Deploy-FabriqUserSetupLauncher
if ($launcherResult) {
    $successCount++
}
else {
    Show-Error "Launcher deployment failed"
    $failCount++
}
Write-Host ""

# --- 5c: Deploy Startup Trigger ---
Write-Host "----------------------------------------" -ForegroundColor White
Write-Host "Deploying Default User Startup trigger" -ForegroundColor Cyan
Write-Host "----------------------------------------" -ForegroundColor White

$triggerResult = Deploy-FabriqStartupTrigger
if ($triggerResult) {
    $successCount++
}
else {
    Show-Error "Startup trigger deployment failed"
    $failCount++
}
Write-Host ""

# ========================================
# Step 6: Result Summary
# ========================================
return (New-BatchResult -Success $successCount -Skip $skipCount -Fail $failCount `
    -Title "Startup Command Deploy Results")
